rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php ./vendor/bin/roadrunner-worker"
  env:
    - XDEBUG_SESSION: "1"

http:
  address: 0.0.0.0:8000
  pool:
    num_workers: 1
    debug: "true"
    max_jobs: 250
    supervisor:
      exec_ttl: 90s
  static:
    dir: "public"
  middleware: ["static"]
  logs:
    mode: "development"
    level: "debug"
    output: "stdout"
    encoding: "json"

status:
  address: 127.0.0.1:2114